/* adFreeCell - precomputed difficulty tiers for deals 1..32000.
 * Placeholder: the real data is generated by tools/rate-difficulty.js (a
 * multi-worker solver run) and replaces this file. Until then, difficulty is
 * simply not shown. Tier string is 1-indexed: 1 Leicht, 2 Mittel, 3 Schwer,
 * 4 Experte, 9 unlösbar, 0/absent = unknown.
 */
window.Difficulty = { pending: true, tiers: "" };
