/* adFreeCell - build the embedded card sprite from the pristine card sources.
 *
 * Reads assets/cards/{rank}{suit}.svg (the "playing-cards-standard-deck" by
 * younestouati, LGPL-3.0) and produces js/cards-sprite.js: one hidden inline
 * SVG holding all 52 cards as <g id="card_{rank}{suit}"> groups, referenced by
 * the game via <use href="#card_1s"> etc.
 *
 * Every source card reuses the ids "suit" and "numeral"; those are namespaced
 * per card here so 52 cards can coexist in one document without collisions.
 *
 * Run:  node tools/build-cards.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const CARDS_DIR = path.join(__dirname, '..', 'assets', 'cards');
const OUT = path.join(__dirname, '..', 'js', 'cards-sprite.js');

const RANKS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
const SUITS = ['c', 'd', 'h', 's'];

// Presentation attributes on the root <svg> (crucially `fill`, which is red for
// hearts/diamonds) are inherited by the child paths. When we drop the root <svg>
// we must re-apply them to the wrapping <g>, or the red suits fall back to black.
const DROP_ATTRS = new Set([
  'version', 'baseProfile', 'xmlns', 'xmlns:xlink', 'viewBox',
  'width', 'height', 'x', 'y', 'id', 'preserveAspectRatio',
]);
function carryAttrs(openTag) {
  const attrs = openTag.replace(/^<svg/, '').replace(/>$/, '');
  const out = [];
  const re = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"/g;
  let m;
  while ((m = re.exec(attrs))) if (!DROP_ATTRS.has(m[1])) out.push(`${m[1]}="${m[2]}"`);
  return out.length ? ' ' + out.join(' ') : '';
}

function buildGroup(name) {
  const file = path.join(CARDS_DIR, name + '.svg');
  let svg = fs.readFileSync(file, 'utf8');
  const openTag = (svg.match(/<svg[^>]*>/) || ['<svg>'])[0];
  // keep only the inner content of the root <svg>…</svg>
  let inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  // namespace the two shared ids and every reference to them
  inner = inner
    .replace(/id="suit"/g, `id="${name}_suit"`)
    .replace(/id="numeral"/g, `id="${name}_numeral"`)
    .replace(/#suit/g, `#${name}_suit`)
    .replace(/#numeral/g, `#${name}_numeral`);
  // Make the red ink controllable from CSS: currentColor lets a "colorblind"
  // theme swap the red suits to a higher-luminance vermilion (distinct from
  // black for red-blind players). Black suits keep the default black fill.
  return `<g id="card_${name}"${carryAttrs(openTag)}>${inner}</g>`.replace(/#d40000/g, 'currentColor');
}

const groups = [];
for (const rank of RANKS) for (const suit of SUITS) groups.push(buildGroup(rank + '' + suit));

const sprite =
  '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ' +
  'style="display:none" aria-hidden="true" width="0" height="0">' + groups.join('') + '</svg>';

const header = `/* adFreeCell - embedded playing-card artwork (SVG sprite).
 *
 * Card artwork: "playing-cards-standard-deck" by younestouati
 *   https://github.com/younestouati/playing-cards-standard-deck
 * Licensed under the GNU LGPL v3.0. The pristine, unmodified per-card sources
 * ship in assets/cards/. See LICENSES/CARDS-NOTICE.md and LICENSES/LGPL-3.0.txt.
 *
 * This file embeds those cards (each <g id="card_1s"> … "card_13h", viewBox
 * 0 0 225 314) so the game runs offline and directly from the filesystem.
 * Ids "suit"/"numeral" are namespaced per card to avoid collisions.
 *
 * GENERATED by tools/build-cards.js - do not edit by hand.
 */
(function () {
  'use strict';
  var MARKUP = ${JSON.stringify(sprite)};
  function inject() {
    if (document.getElementById('card-sprite-host')) return;
    var host = document.createElement('div');
    host.id = 'card-sprite-host';
    host.setAttribute('aria-hidden', 'true');
    host.style.cssText = 'position:absolute;width:0;height:0;overflow:hidden;pointer-events:none';
    host.innerHTML = MARKUP;
    var parent = document.body || document.documentElement;
    parent.insertBefore(host, parent.firstChild);
  }
  if (document.body) inject();
  else document.addEventListener('DOMContentLoaded', inject);
  window.CARDS_SPRITE_INJECT = inject;
})();
`;

fs.writeFileSync(OUT, header);
console.log('Wrote', path.relative(path.join(__dirname, '..'), OUT), '-',
  (fs.statSync(OUT).size / 1024).toFixed(0) + ' KB,', groups.length, 'cards');
